---
Université Paris 1 Panthéon-Sorbonne 

Introduction à Machine Learning

Dr. Nourhène BEN RABAH

---

# Lab 1.  Préparation des données avec Pandas


#### Voici la documentation de la structure de données [`DataFrame`](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.html) de Pandas.


#### Vous devez envoyer le notebook rempli à Nourhene.Ben-Rabah@univ-paris1.fr , Veuillez indiquer *Nom_Prénom_Lab1_S2I* dans votre sujet.

---

### Partie 1 

#### Etape 0. Importer la bibliothèque Pandas

In [1]:
import pandas as pd



#### Etape 1. Importer le dataset

Vous commencerez par importer le fichier fromage.csv. Pour cela, vous utiliserez la fonction [`read_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

In [54]:
#fromage = pd.read_csv(r'C:\Users\haphu\Documents\M2 MIAGE\Machine Learning\Datasets\fromage.csv', sep = ';')

fromage = pd.read_csv("C:/Users/haphu/Documents/M2 MIAGE/Machine Learning/Datasets/fromage.csv", sep = ';', header = 0)
fromage

,Fromages,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
0,CarredelEst,314,353.5,72.6,26.3,51.6,30.3,21.0,70,20
1,Babybel,314,238.0,209.8,25.1,63.7,6.4,22.6,70,27
2,Beaufort,401,112.0,259.4,33.3,54.9,1.2,26.6,120,41
3,Bleu,342,336.0,211.1,28.9,37.1,27.5,20.2,90,27
4,Camembert,264,314.0,215.9,19.5,103.0,36.4,23.4,60,20
5,Cantal,367,256.0,264.0,28.8,48.8,5.7,23.0,90,30
6,Chabichou,344,192.0,87.2,27.9,90.1,36.3,19.5,80,36
7,Chaource,292,276.0,132.9,25.4,116.4,32.5,17.8,70,25
8,Cheddar,406,172.0,182.3,32.5,76.4,4.9,26.0,110,28
9,Comte,399,92.0,220.5,32.4,55.9,1.3,29.2,120,51
10,Coulomniers,308,222.0,79.2,25.6,63.6,21.1,20.5,80,13
11,Edam,327,148.0,272.2,24.7,65.7,5.5,24.7,80,44
12,Emmental,378,60.0,308.2,29.4,56.3,2.4,29.4,110,45
13,Fr.chevrepatemolle,206,160.0,72.8,18.5,150.5,31.0,11.1,50,16
14,Fr.fondu.45,292,390.0,168.5,24.0,77.4,5.5,16.8,70,20
15,Fr.frais20nat.,80,41.0,146.3,3.5,50.0,20.0,8.3,10,11
16,Fr.frais40nat.,115,25.0,94.8,7.8,64.3,22.6,7.0,30,10
17,Maroilles,338,311.0,236.7,29.1,46.7,3.6,20.4,90,40
18,Morbier,347,285.0,219.0,29.5,57.6,5.8,23.6,80,30
19,Parmesan,381,240.0,334.6,27.5,90.0,5.2,35.7,80,46
20,Petitsuisse40,142,22.0,78.2,10.4,63.4,20.4,9.4,20,10
21,PontlEveque,300,223.0,156.7,23.4,53.0,4.0,21.1,70,22
22,Pyrenees,355,232.0,178.9,28.0,51.5,6.8,22.4,90,25
23,Reblochon,309,272.0,202.3,24.6,73.1,8.1,19.7,80,30
24,Rocquefort,370,432.0,162.0,31.2,83.5,13.3,18.7,100,25
25,SaintPaulin,298,205.0,261.0,23.3,60.4,6.7,23.3,70,26
26,Tome,321,252.0,125.5,27.3,62.3,6.2,21.8,80,20
27,Vacherin,321,140.0,218.0,29.3,49.2,3.7,17.6,80,30
28,Yaourtlaitent.nat.,70,91.0,215.7,3.4,42.9,2.9,4.1,13,14


#### Etape 2. Regarder les premières et les dernières lignes

Regarder les premières et les dernières lignes permet de : 
- Vérifier que l'importation s'est bien passée
- Avoir un apperçu rapide de ce à quoi ressemble notre dataframe

In [55]:
## 5 première lignes
fromage.head(5) 
## 5 dernière ligne
fromage.tail()

,Fromages,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
24,Rocquefort,370,432.0,162.0,31.2,83.5,13.3,18.7,100,25
25,SaintPaulin,298,205.0,261.0,23.3,60.4,6.7,23.3,70,26
26,Tome,321,252.0,125.5,27.3,62.3,6.2,21.8,80,20
27,Vacherin,321,140.0,218.0,29.3,49.2,3.7,17.6,80,30
28,Yaourtlaitent.nat.,70,91.0,215.7,3.4,42.9,2.9,4.1,13,14

En regardant ces lignes, vous avez certainement remarqué que l'importation ne s'est pas bien passée. Donc vous allez importer le dataset correctement. Vous allez utiliser ';' comme délimiteur et spécifier que la première ligne (index 0) contient les noms de colonnes

Vous pouvez vérifier alors une autre fois. 


#### Etape 4. Vérifier les types de chaque colonne

La seconde chose à faire est une petite vérification sur les types de chaque colonne attribués par pandas lors de l'importation, encore une fois pour vérifier que l'importation s'est bien déroulée. Affichez le type de l'ensemble des colonnes

In [32]:
fromage.dtypes

Fromages        object
calories         int64
sodium         float64
calcium        float64
lipides        float64
retinol        float64
folates        float64
proteines      float64
cholesterol      int64
magnesium        int64
dtype: object

#### Etape 5. Quel est le nombre d'observations dans le dataset ?

Combien de lignes et colonnes sont contenues dans notre fichier ?

In [36]:
fromage.shape

(29, 10)

#### Etape 6. Quelles sont les informations concernant le premier fromage du jeu de données ? 

Il est à présent temps d'utiliser la fonction de sélection qui vous sera le plus utile, la méthode [`iloc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html).

In [53]:
fromage.iloc[0]  #iloc travaille avec index
#fromage.loc[Fromages['CarredelEst']]

new            CarredelEst
calories               314
sodium               353.5
calcium               72.6
lipides               26.3
retinol               51.6
folates               30.3
proteines             21.0
cholesterol             70
magnesium               20
Name: 0, dtype: object

#### Etape 7. Modifiez le nom de la variable `Fromages` par `nom_fromage`.

In [57]:
fromage.rename(columns = {'Fromages': 'new'}, inplace = True)
fromage

,new,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
0,CarredelEst,314,353.5,72.6,26.3,51.6,30.3,21.0,70,20
1,Babybel,314,238.0,209.8,25.1,63.7,6.4,22.6,70,27
2,Beaufort,401,112.0,259.4,33.3,54.9,1.2,26.6,120,41
3,Bleu,342,336.0,211.1,28.9,37.1,27.5,20.2,90,27
4,Camembert,264,314.0,215.9,19.5,103.0,36.4,23.4,60,20
5,Cantal,367,256.0,264.0,28.8,48.8,5.7,23.0,90,30
6,Chabichou,344,192.0,87.2,27.9,90.1,36.3,19.5,80,36
7,Chaource,292,276.0,132.9,25.4,116.4,32.5,17.8,70,25
8,Cheddar,406,172.0,182.3,32.5,76.4,4.9,26.0,110,28
9,Comte,399,92.0,220.5,32.4,55.9,1.3,29.2,120,51
10,Coulomniers,308,222.0,79.2,25.6,63.6,21.1,20.5,80,13
11,Edam,327,148.0,272.2,24.7,65.7,5.5,24.7,80,44
12,Emmental,378,60.0,308.2,29.4,56.3,2.4,29.4,110,45
13,Fr.chevrepatemolle,206,160.0,72.8,18.5,150.5,31.0,11.1,50,16
14,Fr.fondu.45,292,390.0,168.5,24.0,77.4,5.5,16.8,70,20
15,Fr.frais20nat.,80,41.0,146.3,3.5,50.0,20.0,8.3,10,11
16,Fr.frais40nat.,115,25.0,94.8,7.8,64.3,22.6,7.0,30,10
17,Maroilles,338,311.0,236.7,29.1,46.7,3.6,20.4,90,40
18,Morbier,347,285.0,219.0,29.5,57.6,5.8,23.6,80,30
19,Parmesan,381,240.0,334.6,27.5,90.0,5.2,35.7,80,46
20,Petitsuisse40,142,22.0,78.2,10.4,63.4,20.4,9.4,20,10
21,PontlEveque,300,223.0,156.7,23.4,53.0,4.0,21.1,70,22
22,Pyrenees,355,232.0,178.9,28.0,51.5,6.8,22.4,90,25
23,Reblochon,309,272.0,202.3,24.6,73.1,8.1,19.7,80,30
24,Rocquefort,370,432.0,162.0,31.2,83.5,13.3,18.7,100,25
25,SaintPaulin,298,205.0,261.0,23.3,60.4,6.7,23.3,70,26
26,Tome,321,252.0,125.5,27.3,62.3,6.2,21.8,80,20
27,Vacherin,321,140.0,218.0,29.3,49.2,3.7,17.6,80,30
28,Yaourtlaitent.nat.,70,91.0,215.7,3.4,42.9,2.9,4.1,13,14

#### Etape 8. Quelles sont les fromages existant dans le jeu de données ?

In [64]:
fromage['new']

0            CarredelEst
1                Babybel
2               Beaufort
3                   Bleu
4              Camembert
5                 Cantal
6              Chabichou
7               Chaource
8                Cheddar
9                  Comte
10           Coulomniers
11                  Edam
12              Emmental
13    Fr.chevrepatemolle
14           Fr.fondu.45
15        Fr.frais20nat.
16        Fr.frais40nat.
17             Maroilles
18               Morbier
19              Parmesan
20         Petitsuisse40
21           PontlEveque
22              Pyrenees
23             Reblochon
24            Rocquefort
25           SaintPaulin
26                  Tome
27              Vacherin
28    Yaourtlaitent.nat.
Name: new, dtype: object

##### Etape 9. Analyse rapide des informations de notre jeu de données

Utilisez les fonctions [`describe`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html) et [`info`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html) pour avoir quelques informations rapides sur les variables de notre dataframe :

In [66]:
fromage.describe()

,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000
mean,300.034483,210.086207,185.734483,24.158621,67.562069,13.010345,20.168966,74.586207,26.965517
std,91.914356,108.678923,72.528882,8.129642,24.163098,11.723339,6.959788,28.245755,11.318388
min,70.000000,22.000000,72.600000,3.400000,37.100000,1.200000,4.100000,10.000000,10.000000
25%,292.000000,140.000000,132.900000,23.400000,51.600000,4.900000,17.800000,70.000000,20.000000
50%,321.000000,223.000000,202.300000,26.300000,62.300000,6.400000,21.000000,80.000000,26.000000
75%,355.000000,276.000000,220.500000,29.100000,76.400000,21.100000,23.400000,90.000000,30.000000
max,406.000000,432.000000,334.600000,33.300000,150.500000,36.400000,35.700000,120.000000,51.000000

In [67]:
fromage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   new          29 non-null     object
 1   calories     29 non-null     int64
 2   sodium       29 non-null     float64
 3   calcium      29 non-null     float64
 4   lipides      29 non-null     float64
 5   retinol      29 non-null     float64
 6   folates      29 non-null     float64
 7   proteines    29 non-null     float64
 8   cholesterol  29 non-null     int64
 9   magnesium    29 non-null     int64
dtypes: float64(6), int64(3), object(1)
memory usage: 2.4+ KB

A partir de ces descriptions, pouvez-vous déterminer le nombre  d'élements non nuls dans dans le jeu de données ?

##### Etape 10. La sélection au sein d'un dataframe

###### a) Nous avons vu comment sélectionner une colonne. En utilisant une écriture similaire, sélectionnez deux colonnes de votre choix.

In [69]:
fromage[['new','calories', 'retinol']]

                   new  calories  retinol
0          CarredelEst       314     51.6
1              Babybel       314     63.7
2             Beaufort       401     54.9
3                 Bleu       342     37.1
4            Camembert       264    103.0
5               Cantal       367     48.8
6            Chabichou       344     90.1
7             Chaource       292    116.4
8              Cheddar       406     76.4
9                Comte       399     55.9
10         Coulomniers       308     63.6
11                Edam       327     65.7
12            Emmental       378     56.3
13  Fr.chevrepatemolle       206    150.5
14         Fr.fondu.45       292     77.4
15      Fr.frais20nat.        80     50.0
16      Fr.frais40nat.       115     64.3
17           Maroilles       338     46.7
18             Morbier       347     57.6
19            Parmesan       381     90.0
20       Petitsuisse40       142     63.4
21         PontlEveque       300     53.0
22            Pyrenees       355     51.5
23           Reblochon       309     73.1
24          Rocquefort       370     83.5
25         SaintPaulin       298     60.4
26                Tome       321     62.3
27            Vacherin       321     49.2
28  Yaourtlaitent.nat.        70     42.9

###### b) En utilisant la méthode [`loc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) sélectionnez et déterminez les fromages qui ont des faibles calories (inférieur à 100) :

In [ ]:
fromage.loc[fromage['calories'] < 100]

###### c) Sélectionnez uniquement les noms de ces fromages

In [ ]:
fromage[['new', 'calories']].loc[fromage['calories'] < 100]

###### d) Sélectionnez à présent les informations décrivant les fromages de moins de 100 calories ayant des proteines >5

In [81]:
fromage.loc[(fromage['calories'] < 100) & (fromage['proteines'] > 5)]

,new,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
15,Fr.frais20nat.,80,41.0,146.3,3.5,50.0,20.0,8.3,10,11

###### e) Sur ces fromages, sélectionnez uniquement leur nom et le nombres de proteines

In [83]:
fromage[['new', 'proteines']].loc[(fromage['calories'] < 100) & (fromage['proteines'] > 5)]

               new  proteines
15  Fr.frais20nat.        8.3

###### f) Pour finir, vous créerez un nouveau dataframe, qui contiendra uniquement les fromages dont le calories supérieur ou égale à 100

In [85]:
new_df = fromage.loc[fromage['calories'] >= 10]
new_df

,new,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
0,CarredelEst,314,353.5,72.6,26.3,51.6,30.3,21.0,70,20
1,Babybel,314,238.0,209.8,25.1,63.7,6.4,22.6,70,27
2,Beaufort,401,112.0,259.4,33.3,54.9,1.2,26.6,120,41
3,Bleu,342,336.0,211.1,28.9,37.1,27.5,20.2,90,27
4,Camembert,264,314.0,215.9,19.5,103.0,36.4,23.4,60,20
5,Cantal,367,256.0,264.0,28.8,48.8,5.7,23.0,90,30
6,Chabichou,344,192.0,87.2,27.9,90.1,36.3,19.5,80,36
7,Chaource,292,276.0,132.9,25.4,116.4,32.5,17.8,70,25
8,Cheddar,406,172.0,182.3,32.5,76.4,4.9,26.0,110,28
9,Comte,399,92.0,220.5,32.4,55.9,1.3,29.2,120,51
10,Coulomniers,308,222.0,79.2,25.6,63.6,21.1,20.5,80,13
11,Edam,327,148.0,272.2,24.7,65.7,5.5,24.7,80,44
12,Emmental,378,60.0,308.2,29.4,56.3,2.4,29.4,110,45
13,Fr.chevrepatemolle,206,160.0,72.8,18.5,150.5,31.0,11.1,50,16
14,Fr.fondu.45,292,390.0,168.5,24.0,77.4,5.5,16.8,70,20
15,Fr.frais20nat.,80,41.0,146.3,3.5,50.0,20.0,8.3,10,11
16,Fr.frais40nat.,115,25.0,94.8,7.8,64.3,22.6,7.0,30,10
17,Maroilles,338,311.0,236.7,29.1,46.7,3.6,20.4,90,40
18,Morbier,347,285.0,219.0,29.5,57.6,5.8,23.6,80,30
19,Parmesan,381,240.0,334.6,27.5,90.0,5.2,35.7,80,46
20,Petitsuisse40,142,22.0,78.2,10.4,63.4,20.4,9.4,20,10
21,PontlEveque,300,223.0,156.7,23.4,53.0,4.0,21.1,70,22
22,Pyrenees,355,232.0,178.9,28.0,51.5,6.8,22.4,90,25
23,Reblochon,309,272.0,202.3,24.6,73.1,8.1,19.7,80,30
24,Rocquefort,370,432.0,162.0,31.2,83.5,13.3,18.7,100,25
25,SaintPaulin,298,205.0,261.0,23.3,60.4,6.7,23.3,70,26
26,Tome,321,252.0,125.5,27.3,62.3,6.2,21.8,80,20
27,Vacherin,321,140.0,218.0,29.3,49.2,3.7,17.6,80,30
28,Yaourtlaitent.nat.,70,91.0,215.7,3.4,42.9,2.9,4.1,13,14

### Partie 2.

##### Etape 11. Création de nouvelles variables

Nous allons créer une nouvelle colonne diététique qui indique si le fromage est bon pour un régime ou non en fonction des critères "nombre de calories < 100" et "nombre de protéines > 5"

In [90]:
fromage['dietetique'] = ((fromage['calories'] < 100) & (fromage['proteines'] > 5)).map({True: 'Oui', False: 'Non'})

fromage

,new,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium,dietetique
0,CarredelEst,314,353.5,72.6,26.3,51.6,30.3,21.0,70,20,Non
1,Babybel,314,238.0,209.8,25.1,63.7,6.4,22.6,70,27,Non
2,Beaufort,401,112.0,259.4,33.3,54.9,1.2,26.6,120,41,Non
3,Bleu,342,336.0,211.1,28.9,37.1,27.5,20.2,90,27,Non
4,Camembert,264,314.0,215.9,19.5,103.0,36.4,23.4,60,20,Non
5,Cantal,367,256.0,264.0,28.8,48.8,5.7,23.0,90,30,Non
6,Chabichou,344,192.0,87.2,27.9,90.1,36.3,19.5,80,36,Non
7,Chaource,292,276.0,132.9,25.4,116.4,32.5,17.8,70,25,Non
8,Cheddar,406,172.0,182.3,32.5,76.4,4.9,26.0,110,28,Non
9,Comte,399,92.0,220.5,32.4,55.9,1.3,29.2,120,51,Non
10,Coulomniers,308,222.0,79.2,25.6,63.6,21.1,20.5,80,13,Non
11,Edam,327,148.0,272.2,24.7,65.7,5.5,24.7,80,44,Non
12,Emmental,378,60.0,308.2,29.4,56.3,2.4,29.4,110,45,Non
13,Fr.chevrepatemolle,206,160.0,72.8,18.5,150.5,31.0,11.1,50,16,Non
14,Fr.fondu.45,292,390.0,168.5,24.0,77.4,5.5,16.8,70,20,Non
15,Fr.frais20nat.,80,41.0,146.3,3.5,50.0,20.0,8.3,10,11,Oui
16,Fr.frais40nat.,115,25.0,94.8,7.8,64.3,22.6,7.0,30,10,Non
17,Maroilles,338,311.0,236.7,29.1,46.7,3.6,20.4,90,40,Non
18,Morbier,347,285.0,219.0,29.5,57.6,5.8,23.6,80,30,Non
19,Parmesan,381,240.0,334.6,27.5,90.0,5.2,35.7,80,46,Non
20,Petitsuisse40,142,22.0,78.2,10.4,63.4,20.4,9.4,20,10,Non
21,PontlEveque,300,223.0,156.7,23.4,53.0,4.0,21.1,70,22,Non
22,Pyrenees,355,232.0,178.9,28.0,51.5,6.8,22.4,90,25,Non
23,Reblochon,309,272.0,202.3,24.6,73.1,8.1,19.7,80,30,Non
24,Rocquefort,370,432.0,162.0,31.2,83.5,13.3,18.7,100,25,Non
25,SaintPaulin,298,205.0,261.0,23.3,60.4,6.7,23.3,70,26,Non
26,Tome,321,252.0,125.5,27.3,62.3,6.2,21.8,80,20,Non
27,Vacherin,321,140.0,218.0,29.3,49.2,3.7,17.6,80,30,Non
28,Yaourtlaitent.nat.,70,91.0,215.7,3.4,42.9,2.9,4.1,13,14,Non

Maintenant, nous allons aborder le traitement d'un DataFrame présentant des problèmes. Vous allez importer le fichier CSV nommé 'fromage_V2'

In [102]:
fr2 = pd.read_csv(r"C:\Users\haphu\Documents\M2 MIAGE\Machine Learning\Datasets\fromage_V2.csv", sep= ';')
fr2 

fromage_V2 = fr2
fromage_V2

,Fromages,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium,unnamed
0,CarredelEst,314.0,353.5,72.6,26.3,51.6,30.3,21.0,70.0,20.0,NaN
1,Babybel,314.0,238.0,209.8,25.1,63.7,6.4,22.6,70.0,27.0,NaN
2,Beaufort,401.0,112.0,259.4,33.3,54.9,1.2,26.6,120.0,41.0,NaN
3,Bleu,342.0,336.0,211.1,28.9,37.1,27.5,20.2,90.0,27.0,NaN
4,Camembert,264.0,314.0,215.9,19.5,103.0,36.4,23.4,60.0,20.0,NaN
5,Cantal,367.0,256.0,264.0,28.8,48.8,5.7,23.0,90.0,30.0,NaN
6,Chabichou,344.0,192.0,87.2,27.9,90.1,36.3,19.5,80.0,36.0,NaN
7,Chaource,292.0,276.0,132.9,25.4,116.4,32.5,17.8,70.0,25.0,NaN
8,Cheddar,406.0,172.0,182.3,32.5,76.4,4.9,26.0,110.0,28.0,NaN
9,Comte,399.0,92.0,220.5,32.4,55.9,1.3,29.2,120.0,51.0,NaN
10,Coulomniers,308.0,222.0,79.2,25.6,63.6,21.1,20.5,80.0,13.0,NaN
11,Edam,327.0,148.0,272.2,24.7,65.7,5.5,24.7,80.0,44.0,NaN
12,Emmental,378.0,60.0,308.2,29.4,56.3,2.4,29.4,110.0,45.0,NaN
13,Fr.chevrepatemolle,206.0,160.0,72.8,18.5,150.5,31.0,11.1,50.0,16.0,NaN
14,Fr.fondu.45,292.0,390.0,168.5,24.0,77.4,5.5,16.8,70.0,20.0,NaN
15,Fr.frais20nat.,80.0,41.0,146.3,3.5,50.0,20.0,8.3,10.0,11.0,NaN
16,Fr.frais40nat.,115.0,25.0,94.8,7.8,64.3,22.6,7.0,30.0,10.0,NaN
17,Maroilles,338.0,311.0,236.7,29.1,46.7,3.6,20.4,90.0,40.0,NaN
18,Morbier,347.0,285.0,219.0,29.5,57.6,5.8,23.6,80.0,30.0,NaN
19,Parmesan,381.0,240.0,334.6,27.5,90.0,5.2,35.7,80.0,46.0,NaN
20,Petitsuisse40,142.0,22.0,78.2,10.4,63.4,20.4,9.4,20.0,10.0,NaN
21,PontlEveque,300.0,223.0,156.7,23.4,53.0,4.0,21.1,70.0,22.0,NaN
22,Pyrenees,355.0,232.0,178.9,28.0,51.5,6.8,22.4,90.0,25.0,NaN
23,Reblochon,309.0,272.0,202.3,24.6,73.1,8.1,19.7,80.0,30.0,NaN
24,Rocquefort,370.0,432.0,162.0,31.2,83.5,13.3,18.7,100.0,25.0,NaN
25,SaintPaulin,298.0,205.0,261.0,23.3,60.4,6.7,23.3,70.0,26.0,NaN
26,Tome,321.0,252.0,125.5,27.3,62.3,6.2,21.8,80.0,20.0,NaN
27,Vacherin,321.0,140.0,218.0,29.3,49.2,3.7,17.6,80.0,30.0,NaN
28,Yaourtlaitent.nat.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### Etape 12. Traitement des valeurs manquantes

Vous avez certainement remarqué, il y une colonne vide 'unnamed' et une ligne avec des valeurs nulles. 

Lorsque vous rencontrez des cases vides (valeurs manquantes) dans un DataFrame, vous avez plusieurs options pour les traiter :

- Suppression des lignes ou des colonnes : Vous pouvez supprimer les lignes ou les colonnes contenant des valeurs manquantes

- Remplissage des valeurs manquantes : Vous pouvez remplir les valeurs manquantes avec une valeur spécifique à l'aide de la méthode fillna() de pandas. Vous pouvez choisir de remplir avec une valeur constante, la moyenne, la médiane ou d'autres méthodes de votre choix.

- Interpolation : Vous pouvez utiliser des méthodes d'interpolation pour estimer les valeurs manquantes en fonction des valeurs voisines dans la colonne...

Le choix de la méthode dépend du contexte de vos données et de l'objectif de votre analyse. Certaines approches peuvent être plus appropriées que d'autres en fonction de la nature des données et des analyses que vous souhaitez effectuer.

###### a) Suppression des lignes ou des colonnes

In [101]:
fr2.dropna(axis=0, inplace=True) # Voir les lignes, si on voir un null, on supprime toute la ligne
fr2.dropna(axis=1, inplace=True) # Voir les colonne, si on voir un colonne vite, supprime toute la colonne

#inplace = mettre à jour

Empty DataFrame
Columns: [Fromages, calories, sodium, calcium, lipides, retinol, folates, proteines, cholesterol, magnesium, unnamed]
Index: []

###### b) Remplissage des valeurs manquantes par la moyenne

In [105]:
moyenne_colonne = fromage_V2['calories'].mean()  
moyenne_colonne
fromage_V2['calories'].fillna(moyenne_colonne, inplace=True)
fromage_V2.tail(5)

,Fromages,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium,unnamed
24,Rocquefort,370.00,432.0,162.0,31.2,83.5,13.3,18.7,100.0,25.0,NaN
25,SaintPaulin,298.00,205.0,261.0,23.3,60.4,6.7,23.3,70.0,26.0,NaN
26,Tome,321.00,252.0,125.5,27.3,62.3,6.2,21.8,80.0,20.0,NaN
27,Vacherin,321.00,140.0,218.0,29.3,49.2,3.7,17.6,80.0,30.0,NaN
28,Yaourtlaitent.nat.,308.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Partie 3. 

#### Exercice 1. Le jeu de données IRIS 

- Importer le jeu de données [`IRIS`](https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv)
- Utilisez les fonctions nécessaires pour visualiser respectivement le début et la fin du DataFrame
- Combien de lignes et de colonnes dans le dataset ? 
- Affichez la troixième ligne et la colonne "sepal_width"
- Affichez la troixième ligne
- Affichez la moyenne de la colonne sepal_length
- Affichez l'ecart type de la colonne sepal_length
- Affichez le minimum de la colonne sepal_length
- Y a-t-il des valeurs manquantes dans le dataset ?
- Fixons les valeurs des lignes 10 à 29 de la colonne "petal_length" à NaN.
- Remplaçons maintenant les valeurs NaN par 1,0
- Définir les 3 premières lignes comme NaN
- Supprimer les lignes contenant des NaN :  [`dropna`](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.dropna.html)
- Renomer la colonne species par class

#### Exercice 2.
Créez un dataFrame Pandas à partir des deux variables déclarées ci-dessous. Les clés du dictionnaire `exam_data` correspondent aux noms des colonnes du DataFrame. La liste de str `labels` correspond à l'index du DataFrame.

Explorez ensuite ce dataFrame pour détecter et nettoyer les éventuelles données manquantes.

In [ ]:
import numpy as np
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['z', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame (exam_data, labels)

#### Exercice 3. 
- Étape 1. Allez sur https://www.kaggle.com/openfoodfacts/world-food-facts/data
- Etape 2. Téléchargez l'ensemble de données sur votre ordinateur et décompressez-le.
- Étape 3. Utilisez le fichier tsv et affectez-le au dataframe appelé "food" (sep='\t')
- Étape 4. Déterminez les résultats de ces lignes sans éxecuter

In [ ]:
food.shape
food.shape[0]
food.columns
food.columns[104]

#### Exercice 4. Exercices supplémentaires

Pour faire des exercices supplémentaire sur la préparation de données avec Pandas, voici des exercices avec des solutions https://github.com/guipsamora/pandas_exercises/tree/master/